// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineStore.Data;

#nullable disable

namespace OnlineStore.Migrations
{
    [DbContext(typeof(OnlineStoreDbContext))]
    partial class OnlineStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OnlineStore.Data.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("OnlineStore.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeliveryAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPrice")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineStore.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Bukett vase klar 210 mm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2020/10/8712012-Bukett-Vase-332x530.png",
                            Name = "Bukett vase klar",
                            Price = 2649
                        },
                        new
                        {
                            Id = 2,
                            Description = "Family vase brun medium, 17 cm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2023/06/209021-406x530.jpg",
                            Name = "Family vase brun medium",
                            Price = 1299
                        },
                        new
                        {
                            Id = 3,
                            Description = "Family vase brun stor, 26 cm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2023/06/209031-426x530.jpg",
                            Name = "Family vase brun stor",
                            Price = 1799
                        },
                        new
                        {
                            Id = 4,
                            Description = "Family vase klar liten 11 cm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2023/01/Galaxie_08-420x530.jpg",
                            Name = "Family vase klar liten",
                            Price = 629
                        },
                        new
                        {
                            Id = 5,
                            Description = "Family vase klar medium 17 cm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2023/01/209020-1-433x530.jpg",
                            Name = "Family vase klar medium",
                            Price = 1049
                        },
                        new
                        {
                            Id = 6,
                            Description = "Family vase klar stor 26 cm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2023/01/209030-1-436x530.jpg",
                            Name = "Family vase klar stor",
                            Price = 1579
                        },
                        new
                        {
                            Id = 7,
                            Description = "Galaxie lykt/vase koks liten 8,5 cm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2023/01/220711-507x530.jpg",
                            Name = "Galaxie lykt/vase koks liten",
                            Price = 529
                        },
                        new
                        {
                            Id = 8,
                            Description = "Galaxie lykt/vase koks medium 16,5 cm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2023/01/220721-489x530.jpg",
                            Name = "Galaxie lykt/vase koks medium",
                            Price = 849
                        },
                        new
                        {
                            Id = 9,
                            Description = "Galaxie lykt/vase koks stor 23 cm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2023/01/220731-497x530.jpg",
                            Name = "Galaxie lykt/vase koks stor",
                            Price = 1149
                        },
                        new
                        {
                            Id = 10,
                            Description = "Liten varm cognac 90 mm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2021/01/Iglo_07-460x530.jpg",
                            Name = "Iglo telykt",
                            Price = 629
                        },
                        new
                        {
                            Id = 11,
                            Description = "Stor varm cognac 220 mm",
                            ImageUrl = "https://www.magnor.no/wp-content/uploads/2021/01/Iglo_06-353x530.jpg",
                            Name = "Iglo stormlykt/vase",
                            Price = 1569
                        });
                });

            modelBuilder.Entity("OnlineStore.Data.Cart", b =>
                {
                    b.HasOne("OnlineStore.Data.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineStore.Data.Product", b =>
                {
                    b.HasOne("OnlineStore.Data.Cart", "Cart")
                        .WithMany("Products")
                        .HasForeignKey("CartId");

                    b.HasOne("OnlineStore.Data.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderId");

                    b.Navigation("Cart");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("OnlineStore.Data.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("OnlineStore.Data.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
